name: Fix Issue Name

on:
  issues:
    types: [ opened, edited ]

jobs:
  check_and_update_title:
    name: Check and Update Title
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue
        run: echo "It is  ${{ github.event_name }} event for issue ${{ context.payload }} ${{context.issue}}";
