name: Fix Issue Name

on:
  issues:
    types: [ opened, edited ]

jobs:
  check_and_update_title:
    name: Check and Update Title
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          script: |
            const {title, number} = context.payload.issue;
            const EAK_Number = `[EAK-${number}]`;
            const newTitle = EAK_Number + ` ${title.replace(/^\[.*?\]/, '')}`;

            if (newTitle !== title) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                title: newTitle
              });
            }