name: Fix Issue Name

on:
  issues:
    types: [ opened, edited ]

jobs:
  check_and_update_title:
    name: Check and Update Title
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(contexts);
